### ISSUE TITLE
"Pattern to Match Files" input field in Action: XML Attachment to JSON does not really filter files by name

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/xml-component#13]
Description: Action: XML Attachment to JSON is processes all found `.xml` no matter if the field "Pattern to Match Files" is filled or not.

Precondition: 
1. .xml file named `example` is placed in folder that is used for first step in SFTP.
2. few xml files with different then `example` name are placed into folder that is used for first step in SFTP.

STR:
1. Create flow SFTP -> xml-comp (Action: XML Attachment to JSON)
2.  Fill "Pattern to Match Files" field with `"example"` and retrieve sample.

AR: all sent via SFTP `.xml` files are processed.

ER: Only one `.xml` file with `example` in it's name is processed.

**Comment by shulkaolka** [comment]
Fixed in branch `fixPatternInputField`

**Comment by dvd-z** [comment]
Confirmed that the filter works now. Tested with multiple input files.

**Comment by stas-fomenko** [comment]
already fixed
