### ISSUE TITLE
Update Sailor to 2.6.7

### ISSUE THREAD

**Issue by kirill-levitskiy** [elasticio/xml-component#37]
PR https://github.com/elasticio/xml-component/pull/36

**Comment by A3a3e1** [comment]
- [ ] Push to platform (while flow with component with 'old' sailor ris running. Do not forget to set component version as 'latest')
- [ ] Create valid creds (if supported in component)
- [ ] Retrieve sample (valid input for each action/trigger)
- [ ] Invalid input for action/trigger (error handling of each action/trigger)
- [ ] Run keen flow (with each action/trigger)
- [ ] Run realtime flow (with each action/trigger)
