### ISSUE TITLE
Error handling improvement

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/xml-component#6]
Description: For invalid xml file (line 25) `Action: XML Attachment to JSON` throws uninformative error, however, error message should be informative.
XML:
`<CostaCatalog xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:user="http://Costa/scripting">
<CostaCruiseCatalog Market="F" Channel="CCK" Currency="EUR" Culture="fr-FR" ExportAvailability="False" Exported="2017-11-08">
<Destination Code="Caribbean" DisplayName="Caraïbes">
<Itinerary Code="FLL05014" DisplayName="Floride (USA), Bahamas, Turks et Caicos">
<Cruise Code="DE07181219" DisplayName="Floride (USA), Bahamas, Turks et Caicos" Ship="DE" DeparturePort="FLL" DepartureDate="2018-12-19T00:00:00+01:00" ArrivalPort="FLL" ArrivalDate="2018-12-26T00:00:00+01:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
</Itinerary>
</Destination>
<Destination Code="Mediterranean" DisplayName="Méditerranée">
<Itinerary Code="VCE06145" DisplayName="Italie, Grèce, Croatie">
<Cruise Code="DE07180401" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-04-01T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-04-08T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180408" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-04-08T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-04-15T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180415" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-04-15T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-04-22T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180422" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-04-22T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-04-29T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180429" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-04-29T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-05-06T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180506" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-05-06T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-05-13T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180513" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-05-13T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-05-20T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180520" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-05-20T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-05-27T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07180930" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-09-30T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-10-07T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07181007" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-10-07T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-10-14T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07181021" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-10-21T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-10-28T00:00:00+02:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07181028" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-10-28T00:00:00+02:00" ArrivalPort="VCE" ArrivalDate="2018-11-04T00:00:00+01:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07181104" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-11-04T00:00:00+01:00" ArrivalPort="VCE" ArrivalDate="2018-11-11T00:00:00+01:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07181111" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-11-11T00:00:00+01:00" ArrivalPort="VCE" ArrivalDate="2018-11-18T00:00:00+01:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
<Cruise Code="DE07181118" DisplayName="Italie, Grèce, Croatie" Ship="DE" DeparturePort="VCE" DepartureDate="2018-11-18T00:00:00+01:00" ArrivalPort="VCE" ArrivalDate="2018-11-25T00:00:00+01:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
</Itinerary
</Destination>
<Destination Code="Transatlantic" DisplayName="Transatlantiques">
<Itinerary Code="VCE05025" DisplayName="Italie, Grèce">
<Cruise Code="DE05181125" DisplayName="Italie, Grèce" Ship="DE" DeparturePort="VCE" DepartureDate="2018-11-25T00:00:00+01:00" ArrivalPort="SVN" ArrivalDate="2018-11-30T00:00:00+01:00" Availability="Y" Sellability="Y" IsImmediateConfirm="N" FlightMandatory="False" HotelMandatory="False"/>
</Itinerary>
</Destination>
</CostaCruiseCatalog>
</CostaCatalog>`

Error message: 
`Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: M
   at error (/home/apprunner/node_modules/sax/lib/sax.js:651:10)
   at strictFail (/home/apprunner/node_modules/sax/lib/sax.js:677:7)
   at beginWhiteSpace (/home/apprunner/node_modules/sax/lib/sax.js:951:7)
   at SAXParser.write (/home/apprunner/node_modules/sax/lib/sax.js:1006:11)
   at Parser.exports.Parser.Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:322:31)
   at Parser.parseString (/home/apprunner/node_modules/xml2js/lib/parser.js:5:59)
   at Promise (/home/apprunner/lib/xml2Json.js:19:16)
   at new Promise (<anonymous>)
   at Object.xml2Json [as process] (/home/apprunner/lib/xml2Json.js:18:12)
   at TaskExec.processAction (/home/apprunner/lib/actions/attachmentToJson.js:69:48)
   at process.internalTickCallback (internal/process/next_tick.js:77:7)`

**Comment by shulkaolka** [comment]
This bug isn't reproduced
